name: ItemRenamer
version: 2.2.3-SNAPSHOT
description: Custom default item names
author: [meiskam, aadnk]

main: org.shininet.bukkit.itemrenamer.ItemRenamerPlugin
database: false
depend: [ProtocolLib]
softdepend: [Vault]

commands:
  ItemRenamer:
    aliases: [renamer, rn]
    description: General ItemRenamer command

permissions:
  itemrenamer.*:
    description: Gives all ItemRenamer permissions
    children:
      itemrenamer.update: true
      itemrenamer.config.*: true
  itemrenamer.config.*:
    description: Allows user to edit, save, or reload configs
    children:
      itemrenamer.config.get: true
      itemrenamer.config.set: true
  itemrenamer.config.get:
    description: Allows user to get configs
    default: op
  itemrenamer.config.set:
    description: Allows user to set or reload configs
    default: op
  itemrenamer.update:
    description: Allows user to update the plugin and view update notices
    default: op