package org.shininet.bukkit.itemrenamer;

class CommandErrorException extends RuntimeException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 4935353435818513642L;

	public CommandErrorException(String message, Throwable cause) {
		super(message, cause);
	}

	public CommandErrorException(String message) {
		super(message);
	}

	public CommandErrorException(Throwable cause) {
		super(cause);
	}
}
